clusterGroup:
  name: devel
  isHubCluster: false

  namespaces:
    - argo-rollouts
    - stackrox
    - policies
    - openshift-pipelines
    - devsecops-ci
    - devsecops-dev
    - devsecops-qa

  subscriptions:
    rhacs-operator:
      name: rhacs-operator  #packageName
      namespace: openshift-operators # operator namespace

    openshift-pipelines:
      name: openshift-pipelines-operator-rh
      namespace: openshift-operators

    quay-bridge-operator:
      name: quay-bridge-operator
      namespace: openshift-operators

  projects:
    - secured
    - ci
    - test-app
#Adding jchraibi #advanced-devsecops to pattern framework
    - spring-petclinic
    - rollouts

  applications:
    acs-secured:
      name: acs-secured
      namespace: stackrox
      project: secured
      path: charts/hub/acs/secured

    argo-rollouts:
      name: argo-rollouts
      namespace: argo-rollouts
      project: rollouts
      path: charts/region/rollouts

    pipelines:
      name: pipelines
      namespace: devsecops-ci
      project: ci
      path: charts/region/pipelines
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets
      overrides:
      - name: devel.image
        value: chat-client:latest
      - name: devel.npmbase
        value: quay.io/hybridcloudpatterns/ubi-npm
      - name: devel.namespace
        value: devsecops-ci
      - name: devel.roxCTLImage
        value: registry.access.redhat.com/advanced-cluster-security/rhacs-roxctl-rhel8:3.71.0-5

    quay-integration:
      name: quay-integration
      namespace: openshift-operators
      project: secured
      path: charts/region/quay

    acs-integration:
      name: acs-integration
      namespace: stackrox
      project: ci
      path: charts/region/acs

    nexus:
      name: nexus
      namespace: devsecops-ci
      project: ci
      path: charts/region/nexus

    reports-repo:
      name: reports-repo
      namespace: devsecops-ci
      project: ci
      path: charts/region/reports

    sonarqube:
      name: sonarqube
      namespace: devsecops-ci
      project: ci
      path: charts/region/sonarqube

    cosign:
      name: cosign
      namespace: devsecops-ci
      project: ci
      path: charts/region/cosign

    rekor:
      name: rekor
      namespace: devsecops-ci
      project: ci
      path: charts/region/rekor

    roxctl:
      name: roxctl
      namespace: devsecops-ci
      project: ci
      path: charts/region/roxctl

#Adding jchraibi #advanced-devsecops to pattern framework
    staging-spring-petclinic:
      name: staging-spring-petclinic
      namespace: devsecops-qa
      project: spring-petclinic
      path: charts/region/stage/spring-petclinic-config

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#
#   project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
