---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: claudiol
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: claudiol
    username: claudiol
    email: claudiol@redhat.com
    dev_revision: main

    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: false

main:
  clusterGroupName: hub
