apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: stone-soup-on-prem-pipeline
spec:
  params:
  - name: dockerfile
    description: Docker file to use for specific build. 
    default: https://raw.githubusercontent.com/devfile-samples/devfile-sample-java-springboot-basic/main/docker/Dockerfile
    type: string
  - name: git-url
    description: URL for Git repository of the application
    default: https://github.com/claudiol/spring-petclinic
    type: string
  - name: output-image
    description: Target registry for the container produced
    default: quay.io/claudiol/spring-petclinic:latest
    type: string
  - name: path-context
    description: Git repository path context to use
    default: .
    type: string
  - name: revision
    description: Revision branch to use 
    default: stone-soup-updates
    type: string
  - name: rebuild
    default: "false"
    type: string
  - name: skip-checks
    default: "false"
    type: string
  - name: shared-secret
    default: "default-push-secret"
    type: string
  - name: hermetic
    description: Execute the build with network isolation
    default: "false"
    type: string
  - name: prefetch-input
    description: Build dependencies to be prefetched by Cachi2
    default: ""
    type: string
  - name: java
    description: Java build
    type: string
    default: "true"
  - name: snyk-secret
    description: Snyk Token Secret Name
    type: string
    default: ""
  - name: IMAGE_URL
    description: IMAGE URL
    type: string
    default: quay.io/claudiol/spring-petclinic:latest
  - name: IMAGE_DIGEST
    description: IMAGE DIGEST
    type: string
    default: ""
  - name: DOCKER_AUTH
    description: DOCKER SECRET
    type: string
    default: "default-push-secret"

  tasks:
  - name: init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: shared-secret
      value: $(params.shared-secret)
    - name: skip-checks
      value: $(params.skip-checks)
    - name: pipelinerun-name
      value: $(context.pipelineRun.name)
    - name: pipelinerun-uid
      value: $(context.pipelineRun.uid)
    taskRef:
      name: init
  - name: clone-repository
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: ["true"]
    runAfter:
      - init
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: "$(params.revision)"
    taskRef:
      name: git-clone
    workspaces:
      - name: output
        workspace: workspace
  - name: prefetch-dependencies
    when:
    - input: $(params.hermetic)
      operator: in
      values: ["true"]
    params:
      - name: input
        value: $(params.prefetch-input)
    runAfter:
      - clone-repository
    taskRef:
      name: prefetch-dependencies
    workspaces:
      - name: source
        workspace: workspace
  - name: build-container
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: DOCKER_AUTH
      value: $(tasks.init.results.container-registry-secret)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    runAfter:
    - prefetch-dependencies
    taskRef:
      name: buildah
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace
  - name: inspect-image
    when:
    - input: $(params.skip-checks)
      operator: in
      values: ["false"]
    runAfter:
    - build-container
    taskRef:
      name: inspect-image
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-container.results.IMAGE_URL)"
      - name: IMAGE_DIGEST
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: DOCKER_AUTH
        value: "$(tasks.init.results.container-registry-secret)"
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace
