kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: spring-petclinic
  namespace: devsecops-dev
  labels:
    app: spring-petclinic
    argocd.argoproj.io/instance: spring-petclinic
spec:
  to:
    kind: Service
    name: spring-petclinic
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
