apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "6"
  name: hub-devel-copy-acs-token
  namespace: stackrox
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          '/tmp/copy-acs-token.sh'
        name: copy-acs-token
        volumeMounts:
          - mountPath: /tmp/copy-acs-token.sh
            name: copy-acs-token
            subPath: copy-acs-token.sh
      volumes:
        - name: copy-acs-token
          configMap:
            name: copy-acs-token
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: {{ include "all-in-one.serviceAccountName" . }}
      terminationGracePeriodSeconds: 60
