apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "6"
  name: hub-devel-copy-acs-token
  namespace: stackrox
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          echo "Checking for acs-api-token existence"
          EXISTS=$(oc get secret acs-api-token -n stackrox > /dev/null 2>&1;echo $?)
          while [ $EXISTS -ne 0 ]; then
            sleep 2
            # copy acs-api-token secret into pipeline namespace
            EXISTS=$(oc get secret acs-api-token -n stackrox > /dev/null 2>&1;echo $?)
          done
          EXISTS=$(oc get secret acs-api-token -n devsecops-ci > /dev/null 2>&1;echo $?)
          if [ $EXISTS -ne 0 ]; then
            oc get secret acs-api-token --namespace=stackrox -oyaml | grep -v '\s*namespace:\s' |oc apply --namespace=devsecops-ci -f -
          else
            echo "The acs-api-token secret already exists in namespace devsecops-ci"
          fi
        name: copy-acs-token
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: {{ include "all-in-one.serviceAccountName" . }}
      terminationGracePeriodSeconds: 60
